import type { PreferenceFieldDefinition } from "./types.js";

/**
 * Versioned preference catalog — source of truth for validation + UI.
 * Dynamic selectors (model / aspect / resolution) are UI metadata only.
 */
export const PREFERENCE_CATALOG_VERSION = 1;

export const PREFERENCE_CATALOG: PreferenceFieldDefinition[] = [
  {
    id: "niche",
    type: "single-select",
    title: "What type of content is this?",
    description: "Helps the AI understand the target audience and thumbnail style.",
    options: [
      "Technology",
      "Programming",
      "AI",
      "Gaming",
      "Finance",
      "Business",
      "Education",
      "Fitness",
      "Podcast",
      "Travel",
      "Food",
      "Automotive",
      "Sports",
      "Movies",
      "News",
      "Science",
      "Music",
      "Other",
    ],
  },
  {
    id: "mood",
    type: "single-select",
    title: "What feeling should the thumbnail create?",
    description: "Defines the emotional tone of the generated thumbnail.",
    options: [
      "Exciting",
      "Curious",
      "Shocking",
      "Urgent",
      "Professional",
      "Friendly",
      "Luxury",
      "Minimal",
      "Dark",
      "Energetic",
      "Funny",
      "Mysterious",
      "Inspirational",
    ],
  },
  {
    id: "visualStyle",
    type: "single-select",
    title: "Choose a visual style",
    description: "Determines the overall artistic direction of the thumbnail.",
    options: [
      "Photorealistic",
      "Cinematic",
      "Modern",
      "Minimal",
      "3D Render",
      "Illustration",
      "Anime",
      "Comic",
      "Cyberpunk",
      "Retro",
      "Neon",
      "Documentary",
      "MrBeast Style",
    ],
  },
  {
    id: "primaryColor",
    type: "single-select",
    title: "Choose a dominant color",
    description: "Sets the primary accent color for the thumbnail.",
    options: [
      "Auto",
      "Blue",
      "Red",
      "Yellow",
      "Orange",
      "Green",
      "Purple",
      "Pink",
      "Black",
      "White",
      "Gold",
    ],
  },
  {
    id: "backgroundStyle",
    type: "single-select",
    title: "Choose a background style",
    description: "Controls the appearance of the background.",
    options: [
      "Auto",
      "Blurred",
      "Solid Color",
      "Gradient",
      "Studio",
      "Gaming Room",
      "Office",
      "City",
      "Nature",
      "Abstract",
      "Space",
      "Cyberpunk",
    ],
  },
  {
    id: "lighting",
    type: "single-select",
    title: "Choose a lighting style",
    description: "Determines the lighting and atmosphere.",
    options: [
      "Natural",
      "Studio",
      "Soft",
      "High Contrast",
      "Dramatic",
      "Golden Hour",
      "Neon",
      "Dark",
      "Volumetric",
    ],
  },
  {
    id: "composition",
    type: "single-select",
    title: "Choose a composition",
    description: "Controls how the subject is positioned in the image.",
    options: [
      "Centered",
      "Rule of Thirds",
      "Close-up",
      "Extreme Close-up",
      "Split Layout",
      "Left Focus",
      "Right Focus",
      "Wide Shot",
    ],
  },
  {
    id: "faceEmphasis",
    type: "single-select",
    title: "How prominent should the face be?",
    description:
      "Useful for thumbnails where facial expressions drive engagement.",
    options: ["None", "Subtle", "Medium", "Strong", "Extreme"],
  },
  {
    id: "includeText",
    type: "boolean",
    title: "Should the thumbnail include text?",
    description: "Determines whether the generated thumbnail should contain text.",
    options: ["Yes", "No"],
  },
  {
    id: "textStyle",
    type: "single-select",
    title: "Choose a text style",
    description: "Applied only when text is enabled.",
    dependsOn: { field: "includeText", value: "Yes" },
    options: [
      "Bold",
      "Modern",
      "Minimal",
      "Gaming",
      "Luxury",
      "Outline",
      "Gradient",
      "Glow",
      "3D",
    ],
  },
  {
    id: "textContent",
    type: "text",
    title: "What text should appear?",
    description: "Optional overlay text to include in the thumbnail.",
    placeholder: "React in 15 Minutes",
    dependsOn: { field: "includeText", value: "Yes" },
  },
  {
    id: "model",
    type: "dynamic-select",
    title: "Choose an AI model",
    description: "Options come from visible generation models.",
    source: "generationModels.visible",
  },
  {
    id: "aspectRatio",
    type: "dynamic-select",
    title: "Choose an aspect ratio",
    description: "Available options are determined by the selected AI model.",
    source: "selectedModel.supportedAspectRatios",
    dependsOn: { field: "model", value: "*" },
  },
  {
    id: "resolution",
    type: "dynamic-select",
    title: "Choose an output resolution",
    description: "Available options are determined by the selected AI model.",
    source: "selectedModel.supportedResolutions",
    dependsOn: { field: "model", value: "*" },
  },
];

export function getPromptEmbeddedPreferenceIds(): string[] {
  return PREFERENCE_CATALOG.filter((f) => f.type !== "dynamic-select").map(
    (f) => f.id,
  );
}

export function getPreferenceOptions(id: string): string[] | undefined {
  return PREFERENCE_CATALOG.find((f) => f.id === id)?.options;
}
